### ISSUE TITLE
Meteor(React): From where to pass lat long to google map ? 

### ISSUE THREAD

**Issue by rashmimhatre100** [dburles/meteor-google-maps-react-example#6]
Map is appearing as per expectation. But I am clueless from where to send lat long to api?
I know it in Blaze but not in React.
Thanks in Advance!

**Comment by rashmimhatre100** [comment]
Followed the procedure given in document - [reactive-google-map](http://meteorcapture.com/how-to-create-a-reactive-google-map/). At first I was able to see pins on click but I don't want it on click rather I want it on onRender/document ready. But now I am unable to see any pins. 

**markers** collection have lat-long but pins are not visible.

**Comment by dburles** [comment]
Hey @rashmimhatre100 this is where you pass the initial map options:  https://github.com/dburles/meteor-google-maps-react-example/blob/master/imports/MyMap.js#L14

**Comment by rashmimhatre100** [comment]
Thank you. One has to pass data from collection like Markers in example.
