### ISSUE TITLE
Problems with the googleMaps component in react

### ISSUE THREAD

**Issue by famigone** [dburles/meteor-google-maps-react-example#7]
I am getting this error in last version of Meteor and React:
`GoogleMap.js:44 Uncaught TypeError: Cannot read property 'bool' of undefined at GoogleMap.js`

I even tried this change: 

```
export default GoogleMapContainer = withTracker(
  () => ({ loaded: GoogleMaps.loaded() }),
  GoogleMap,
```
);

**Comment by dburles** [comment]
Hey @famigone I noticed you're not using `withTracker` correctly in your example. Not sure if that's the exact problem you're seeing. Do you have a simple example app that reproduces the issue?

```js
export default GoogleMapContainer = withTracker(
  () => ({ loaded: GoogleMaps.loaded() })
)(GoogleMap);
```

**Comment by famigone** [comment]
Thanks for your answer David. I tried for many hours, in the end, I changed the library.
